name: portfolio
description: A new Flutter project.


publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  
  
  flutter:
    sdk: flutter
  
  google_fonts: ^3.0.1
  animated_text_kit: ^4.2.2
  flutter_animated_button: ^2.0.1
  flutter_animation_progress_bar: ^2.2.1
  dashed_circular_progress_bar: ^0.0.4
  url_launcher: ^6.1.5
  fluttertoast: ^8.0.9
  carousel_slider: ^4.1.1
  smooth_page_indicator: ^1.0.0+2
  firebase_core: ^1.23.0
    
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/